config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "reviews#index"
  # カテゴリー検索ルート
  get '/reviews/displacement/:id', to: "reviews#displacement"
  get '/reviews/maker/:id', to: "reviews#maker"
  get '/reviews/type/:id', to: "reviews#type"
  # いいね機能ルート
  post   '/like/:review_id' => 'likes#like',   as: 'like'
  delete '/like/:review_id' => 'likes#unlike', as: 'unlike'
  resources :reviews do
    collection do
      get 'search'
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show

  # ゲストログイン機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review, counter_cache: :likes_count
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_variables

  # お気に入り登録
  def like
    like = current_user.likes.new(review_id: @review.id)
    like.save
  end

  # お気に入り解除
  def unlike
    like = current_user.likes.find_by(review_id: @review.id)
    like.destroy
  end

  private
  # Ajax非同期通信のため
  def set_variables
    @review = Review.find(params[:review_id])
    @id_name = "#like-link-#{@review.id}"
  end
end

app/helpers/like_helper.rb
module LikeHelper
end

app/views/likes/_like.html.erb
<div class="option" id="like-link-<%= @review.id %>">
  <% if current_user.likes.find_by(review_id: @review.id) %>
    <%= link_to unlike_path(@review.id), method: :delete, remote: true, class:"fav" do %>
      <div class="unfav-btn-field">
        <%= image_tag 'ungood.png', class: "favorite-btn", width:"20", height:"20" %>
        お気に入り解除
      </div>
    <% end %>
  <% else %>
    <%= link_to like_path(@review.id), method: :post, remote: true, class:"fav" do %>
      <div class="fav-btn-field">
        <%= image_tag 'good.png', class: "favorite-btn", width:"20", height:"20" %>
        お気に入り
      </div>
    <% end %>
  <% end %>
  <div class="fav-counter">
    お気に入り数：<%= @review.likes.count %>
  </div>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", review: @review )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", review: @review )) %>');