config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "reviews#index"
  # カテゴリー検索ルート
  get '/reviews/displacement/:id', to: "reviews#displacement"
  get '/reviews/maker/:id', to: "reviews#maker"
  get '/reviews/type/:id', to: "reviews#type"
  # いいね機能ルート
  post   '/like/:review_id' => 'likes#like',   as: 'like'
  delete '/like/:review_id' => 'likes#unlike', as: 'unlike'
  resources :reviews do
    collection do
      get 'search'
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show

  # ゲストログイン機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='bikke-details'>
      <h2 class='footer-content-head'>BIKKE!!について</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'BIKKE!!利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='bikke-details'>
      <h2 class='footer-content-head'>ライダーレビューを探す</h2>
      <ul>
        <li><%= link_to '車種一覧', "#", class: "footer-link" %></li>
        <li><%= link_to '排気量一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'メーカー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to '車種タイプ一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='bikke-details'>
      <h2 class='footer-content-head'>BIKKE!!について</h2>
      <ul>
        <li><%= link_to 'BIKKE!!ガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'BIKKE!!ロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("BIKKE!!logo.png", class:"logo-white"), "#" %>
  <p>© BIKKE!!</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <%= link_to image_tag("BIKKE!!logo.png", class:"bikke-icon"), root_path, class: "logo" %>
  <div class='nav'>
    <ul class='lists-signin'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
        <li><%= link_to "Post", new_review_path, class: "post-review" %></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %> 
        <li><%= link_to 'Guest', users_guest_sign_in_path, method: :post, class: "guestlogin" %></li>
        <li><%= link_to 'Sign in', new_user_session_path, class: "login" %></li>
        <li><%= link_to 'Sign up', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_search-list.html.erb
<div class='search-contents'>
  <div class='bike-search'>
    <div class="bike-title">▶︎　車種名から探す</div>
      <%= search_form_for @r, url: search_reviews_path do |f| %>
        <%= f.search_field :bike_cont, placeholder: "車種名", class: "search-field" %>
        <%= f.submit "検索", class: "search-btn" %>
      <% end %>
  </div>
  <div class='displacement-search'>
    <div class="displacement-title">▶︎　排気量から探す</div>
    <ul class="displacement-list1">
      <%= link_to "50cc以下", '/reviews/displacement/1', class: "displacement" %>
      <%= link_to "51~125cc", '/reviews/displacement/2', class: "displacement" %>
      <%= link_to "126~250cc", '/reviews/displacement/3', class: "displacement" %>
      <%= link_to "251~400cc", '/reviews/displacement/4', class: "displacement" %>
    </ul>
    <ul class="displacement-list2">
      <%= link_to "401~750cc", '/reviews/displacement/5', class: "displacement" %>
      <%= link_to "751~1000cc", '/reviews/displacement/6', class: "displacement" %>
      <%= link_to "1000cc以上", '/reviews/displacement/7', class: "displacement" %>
    </ul>
  </div>
  <div class='maker-search'>
    <div class="maker-title">▶︎　メーカーから探す</div>
    <ul class="maker-list1">
      <%= link_to "HONDA", '/reviews/maker/1', class: "maker" %>
      <%= link_to "YAMAHA", '/reviews/maker/2', class: "maker" %>
      <%= link_to "SUZUKI", '/reviews/maker/3', class: "maker" %>
      <%= link_to "KAWASAKI", '/reviews/maker/4', class: "maker" %>
      <%= link_to "DOCATI", '/reviews/maker/5', class: "maker" %>
    </ul>
    <ul class="maker-list2">
      <%= link_to "BMW", '/reviews/maker/6', class: "maker" %>
      <%= link_to "Harley-Davidson", '/reviews/maker/7', class: "maker" %>
      <%= link_to "TRIUMPH", '/reviews/maker/8', class: "maker" %>
      <%= link_to "KTM", '/reviews/maker/9', class: "maker" %>
      <%= link_to "aprilia", '/reviews/maker/10', class: "maker" %>
    </ul>
    <ul class="maker-list3">
      <%= link_to "MOTO GUZZI", '/reviews/maker/11', class: "maker" %>
      <%= link_to "MV Agusta", '/reviews/maker/12', class: "maker" %>
      <%= link_to "Vespa", '/reviews/maker/13', class: "maker" %>
      <%= link_to "Indian", '/reviews/maker/14', class: "maker" %>
      <%= link_to "KYMCO", '/reviews/maker/15', class: "maker" %>
    </ul>
    <ul class="maker-list4">
      <%= link_to "Buell", '/reviews/maker/16', class: "maker" %>
      <%= link_to "bimota", '/reviews/maker/17', class: "maker" %>
      <%= link_to "Husqvana", '/reviews/maker/18', class: "maker" %>
      <%= link_to "その他", '/reviews/maker/19', class: "maker" %>
    </ul>
  </div>
  <div class='mototype-search'>
    <div class="mototype-title">▶︎　タイプから探す</div>
    <ul class="mototype-list1">
      <li class="mototype">
        <%= link_to image_tag("SS.png", class:"list-pict"), "/reviews/type/1" %>
        スーパースポーツ</li>
      <li class="mototype">
        <%= link_to image_tag("naked.png", class:"list-pict"), "/reviews/type/2" %>
        ネイキッド</li>
      <li class="mototype">
        <%= link_to image_tag("american.png", class:"list-pict"), "/reviews/type/3" %>
        アメリカン</li>
      <li class="mototype">
        <%= link_to image_tag("street.png", class:"list-pict"), "/reviews/type/4" %>
        ストリート</li>
    </ul>
    <ul class="mototype-list2">
      <li class="mototype">
        <%= link_to image_tag("offroad.png", class:"list-pict"), "/reviews/type/5" %>
        オフロード</li>
      <li class="mototype">
        <%= link_to image_tag("motard.png", class:"list-pict"), "/reviews/type/6" %>
        モタード</li>
      <li class="mototype">
        <%= link_to image_tag("scooter.png", class:"list-pict"), "/reviews/type/7" %>
        スクーター</li>
      <li class="mototype">
        <%= link_to image_tag("trike.png", class:"list-pict"), "/reviews/type/8" %>
        トライク</li>
      <li class="mototype">
        <%= link_to image_tag("other.png", class:"list-pict"), "/reviews/type/9" %>
        その他</li>
    </ul>
  </div>
  <div class="refined-serach">
    <div class="refined-title">▶︎　絞り込み検索</div>
    <%= search_form_for @r, url: search_reviews_path do |f| %>
      <div class="refined-label">
        <%= f.label :displacement_id_eq, '排気量　　' %>
        <%= f.collection_select :displacement_id_eq, Displacement.all, :id, :name, prompt: '指定なし' %>
      </div>
      <div class="refined-label">
        <%= f.label :maker_id_eq, 'メーカー　' %>
        <%= f.collection_select :maker_id_eq, Maker.all, :id, :name, prompt: '指定なし' %>
      </div>
      <div class="refined-label">
        <%= f.label :type_id_eq, '車種タイプ' %>
        <%= f.collection_select :type_id_eq, Type.all, :id, :name, prompt: '指定なし' %>
      </div>
      <%= f.submit '検索', class:"search-btn" %>
    <% end %>
  </div>
</div>

app/views/shared/_second_footer.html.erb
<footer class='second-fotter'>
  <%= image_tag "BIKKE!!logo.png", class:"second-fotter-logo"%>
    <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>Copyright©︎BIKKE inc. All Rights Reserved</p>
  </div>
</footer>

app/views/shared/_second_header.html.erb
<header class='second-header'>
  <%= link_to image_tag("BIKKE!!logo.png", class:"second-logo"), root_path %>
</header>

app/views/shared/_star_eval.html.erb
<%# レビュー詳細 %>
<script>
  $('#star-comf-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= @review.comfort %>,
  });
</script>
<script>
  $('#star-fuel-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= @review.fuel %>,
  });
</script>
<script>
  $('#star-mainte-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= @review.maintenance %>,
  });
</script>
<script>
  $('#star-cost-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= @review.cost %>,
  });
</script>
<script>
  $('#star-speed-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= @review.speed %>,
  });
</script>
<script>
  $('#star-look-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= @review.look %>,
  });
</script>
<script>
  $('#star-reco-<%= @review.id %>').raty({
    size: 60,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= @review.recommend %>,
  });
</script>
<%# /レビュー詳細 %>
<%# 編集画面 %>
<script>
  $('#edit-comf-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    score: <%= @review.comfort %>,
    scoreName: 'review[comfort]',
  });
</script>
<script>
  $('#edit-fuel-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    score: <%= @review.fuel %>,
    scoreName: 'review[fuel]',
  });
</script>
<script>
  $('#edit-mainte-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    score: <%= @review.maintenance %>,
    scoreName: 'review[maintenance]',
  });
</script>
<script>
  $('#edit-cost-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    score: <%= @review.cost %>,
    scoreName: 'review[cost]',
  });
</script>
<script>
  $('#edit-speed-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    score: <%= @review.speed %>,
    scoreName: 'review[speed]',
  });
</script>
<script>
  $('#edit-look-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    score: <%= @review.look %>,
    scoreName: 'review[look]',
  });
</script>
<script>
  $('#edit-reco-<%= @review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    score: <%= @review.recommend %>,
    scoreName: 'review[recommend]',
  });
</script>
<%# /編集画面 %>

app/views/shared/_star_eval_new.html.erb
<%# 新規レビュー投稿 %>
<script>
$('#star1').raty({
  size     : 38,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'review[comfort]',
  half: true,
});
</script>
<script>
$('#star2').raty({
  size     : 38,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'review[fuel]',
  half: true,
});
</script>
<script>
$('#star3').raty({
  size     : 38,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'review[maintenance]',
  half: true,
});
</script>
<script>
$('#star4').raty({
  size     : 38,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'review[cost]',
  half: true,
});
</script>
<script>
$('#star5').raty({
  size     : 38,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'review[speed]',
  half: true,
});
</script>
<script>
$('#star6').raty({
  size     : 38,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'review[look]',
  half: true,
});
</script>
<script>
$('#star7').raty({
  size     : 38,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'review[recommend]',
  half: true,
});
</script>
<%# /新規レビュー投稿 %>